version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - make package
      - aws cloudformation package --template-file ./stacks/vatsim-data-account/main.yml --s3-bucket $ARTIFACTS_BUCKET --s3-prefix artifacts/vatsim-data-api-proxy --output-template-file ./stacks/vatsim-data-account/main.yml
artifacts:
  files: "**/*"
